name: Latest Medium posts workflow
on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  update-readme-with-medium-posts:
    name: Update README.md with my latest Medium blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          commit_message: "Updated README.md with latest Medium blog posts"
          feed_list: "https://medium.com/feed/@techyArsal"
